version: '3.8'

services:
  # 1. Broker MQTT Customizado (O coração da ingestão LoRa)
  # Desenvolvido em Go para alta performance e baixo consumo
  mqtt-broker:
    build: ./mqtt-broker
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"      # Porta MQTT padrão
      - "8883:8883"      # Porta para TLS/SSL (Futuro)
    volumes:
      - ./data/broker:/root/data/db # Persistência das Retained Messages
    networks:
      - smartfarm-network

  # 2. RabbitMQ (Barramento de Eventos)
  # Garante que o sistema suporte o ODS 9 com infraestrutura resiliente
  rabbitmq:
    image: rabbitmq:3-management
    container_name: barramento-de-eventos
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - smartfarm-network
    healthcheck: # Garante que o serviço está REALMENTE pronto
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-rabbit:
    build: 
      context: .
      dockerfile: ./barramento-de-eventos # O Dockerfile que roda o config_rabbit.go
    depends_on:
      rabbitmq:
        condition: service_healthy # Só roda quando o RabbitMQ passar no healthcheck
    networks:
      - smartfarm-network

# Rede isolada para comunicação segura entre os containers
networks:
  smartfarm-network:
    driver: bridge